//! Deterministic minified/generated content classification (WI063
//! ROG-022, Decision 0048). Classification is policy, not a semantic
//! fact -- these functions decide whether a file's *content shape*
//! warrants skipping parse, never anything about what the content means.
//! Thresholds are centralized here (not scattered per adapter) and
//! deliberately conservative pending real measurement evidence, exactly
//! like `semantic::ResourcePolicy`'s existing constants.

/// A file at or above this size, with no newline found in it at all, is
/// treated as minified regardless of line-length heuristics -- a single
/// multi-kilobyte line is definitionally not hand-authored source.
pub const MINIFIED_MIN_CONTENT_BYTES: usize = 4096;
/// Average line length (bytes) above which content already past the
/// minimum-size threshold is treated as minified.
pub const MINIFIED_AVERAGE_LINE_LENGTH_THRESHOLD: usize = 500;
/// Only the first N bytes are scanned for a generated-content marker --
/// bounded, not a full-file scan, consistent with ROG-022's resource
/// discipline.
pub const GENERATED_MARKER_SCAN_BYTES: usize = 1024;

const GENERATED_MARKERS: [&str; 6] = [
    "generated by",
    "@generated",
    "do not edit",
    "auto-generated",
    "autogenerated",
    "this file is automatically generated",
];

/// Deterministic minified-content classification. Bounded to counting
/// bytes/newlines in the already-loaded, already-size-capped content --
/// no additional file I/O, no unbounded scan.
pub fn is_probably_minified(content: &[u8]) -> bool {
    if content.len() < MINIFIED_MIN_CONTENT_BYTES {
        return false;
    }
    let newline_count = content.iter().filter(|byte| **byte == b'\n').count();
    if newline_count == 0 {
        return true;
    }
    let average_line_length = content.len() / (newline_count + 1);
    average_line_length > MINIFIED_AVERAGE_LINE_LENGTH_THRESHOLD
}

/// Deterministic generated-content classification: a case-insensitive
/// substring search over a bounded prefix of the content for a small,
/// documented set of conventional generator markers. Specific enough
/// ("generated by", "@generated") that ordinary prose using the word
/// "generate" in an unrelated sentence does not false-positive.
pub fn is_probably_generated(content: &[u8]) -> bool {
    let scan_len = content.len().min(GENERATED_MARKER_SCAN_BYTES);
    let head = String::from_utf8_lossy(&content[..scan_len]).to_lowercase();
    GENERATED_MARKERS.iter().any(|marker| head.contains(marker))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_large_single_line_file_is_classified_minified() {
        let content = vec![b'x'; MINIFIED_MIN_CONTENT_BYTES + 100];
        assert!(is_probably_minified(&content));
    }

    #[test]
    fn a_large_file_with_long_average_lines_is_classified_minified() {
        let line = "x".repeat(MINIFIED_AVERAGE_LINE_LENGTH_THRESHOLD + 50);
        // Enough repeated long lines to clear MINIFIED_MIN_CONTENT_BYTES
        // as well as the average-line-length threshold -- a file must
        // fail *both* checks to be exempt, so the fixture must be large
        // enough to actually exercise the average-length branch.
        let content = format!("{line}\n").repeat(20).into_bytes();
        assert!(content.len() >= MINIFIED_MIN_CONTENT_BYTES);
        assert!(is_probably_minified(&content));
    }

    #[test]
    fn ordinary_multi_line_source_is_not_classified_minified() {
        let content = "pub fn hello() {\n    println!(\"hi\");\n}\n".repeat(200);
        assert!(!is_probably_minified(content.as_bytes()));
    }

    #[test]
    fn small_single_line_content_is_not_classified_minified() {
        // Below the minimum-size threshold -- a short one-liner is not
        // minified, it is just short.
        let content = b"pub fn f() {}";
        assert!(!is_probably_minified(content));
    }

    #[test]
    fn a_recognized_generator_header_is_classified_generated() {
        let content = b"// Generated by repopact-desktop-api. Do not edit by hand.\nexport type X = string;\n";
        assert!(is_probably_generated(content));
    }

    #[test]
    fn ordinary_prose_mentioning_generate_is_not_classified_generated() {
        let content = b"// This function will generate a report for the user.\nfn report() {}\n";
        assert!(!is_probably_generated(content));
    }

    #[test]
    fn a_generator_marker_outside_the_scan_window_is_not_detected() {
        let padding = "x".repeat(GENERATED_MARKER_SCAN_BYTES + 100);
        let content = format!("{padding}\n// @generated\n").into_bytes();
        assert!(
            !is_probably_generated(&content),
            "the bounded scan window must not grow unboundedly to find a \
             marker far into a large file -- this is deliberate, not a bug"
        );
    }
}
