[package]
name = "repopact-mutation"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
repopact-graph.workspace = true
repopact-repository.workspace = true
repopact-types.workspace = true
repopact-validation.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
